---
resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: jtarchie/pr

resources:
  - name: super-app
    type: pull-request
    source:
      repo: dohernandez/concourse-tutorial
      access_token: {{github_token}}

jobs:
  - name: testing
    plan:

    - get: super-app
      trigger: true

    # Make a context "unit tests" status pending in Github Pull request
    - put: super-app
      params: {path: super-app, context: Unit tests, status: pending}

    - aggregate: # parallelisms running
      - task: lint
        file: super-app/tutorial/scenario.1/1-list/tasks/lint.yml

      - task: run unit
        file: super-app/tutorial/scenario.1/1-list/tasks/unit.yml

  - name: building & integration test
    plan:

    - get: super-app
      passed: ["testing"] # List of dependencies job. The jobs have to pass before to execute this job
      trigger: true

    - task: build
      file: super-app/tutorial/scenario.1/1-list/tasks/build.yml

    - task: integration test
      file: super-app/tutorial/scenario.1/1-list/tasks/integration_test.yml
