---
resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: jtarchie/pr

resources:
  - name: pull-request
    type: pull-request
    source:
      repo: dohernandez/concourse-tutorial
      access_token: {{github_token}}
  - name: release-rc
    type: github-release
    source:
      repo: dohernandez/concourse-tutorial
      access_token: {{github_token}}

jobs:
  - name: testing
    plan:

    - get: pull-request
      trigger: true

    # Make a context "unit tests" status pending in Github Pull request
    - put: pull-request
      params: {path: pull-request, context: testing, status: pending}

    - aggregate: # parallelisms running
      - task: run lint
        file: pull-request/tutorial/scenario.1/1-list/tasks/lint.yml
        on_success:
          put: pull-request
          params: {path: pull-request, context: lint, status: success}
        on_failure:
          put: pull-request
          params: {path: pull-request, context: lint, status: failure}

      - task: run unit
        file: pull-request/tutorial/scenario.1/1-list/tasks/unit.yml
        on_success:
          put: pull-request
          params: {path: pull-request, context: unit, status: success}
        on_failure:
          put: pull-request
          params: {path: pull-request, context: unit, status: failure}

    on_success:
      put: pull-request
      params: {path: pull-request, context: testing, status: success}
    on_failure:
      put: pull-request
      params: {path: pull-request, context: testing, status: failure}

  - name: building & integration test
    plan:

    - get: pull-request
      passed: ["testing"] # List of dependencies job. The jobs have to pass before to execute this job
      trigger: true

    - task: run build
      file: pull-request/tutorial/scenario.1/1-list/tasks/build.yml
      on_success:
        put: pull-request
        params: {path: pull-request, context: build, status: success}
      on_failure:
        put: pull-request
        params: {path: pull-request, context: build, status: failure}

    - task: run integration test
      file: pull-request/tutorial/scenario.1/1-list/tasks/integration_test.yml
      on_success:
        put: pull-request
        params: {path: pull-request, context: integration test, status: success}
      on_failure:
        put: pull-request
        params: {path: pull-request, context: integration test, status: failure}

    on_success:
      put: pull-request
      params: {path: pull-request, context: building & integration test, status: success}
    on_failure:
      put: pull-request
      params: {path: pull-request, context: building & integration test, status: failure}
