---
platform: linux
image_resource:
  type: docker-image
  source: {repository: golang}
inputs:
  - name: pull-request
  - name: artifact
run:
  path: sh
  args:
    - -exc
    - |
      ./artifact/super_*_linux_amd64&
      ./pull-request/scripts/test_integration.sh http://127.0.0.1:8080
      kill -9 `pgrep super_`