---
platform: linux
image_resource:
  type: docker-image
  source: {repository: golang}
inputs:
  - name: pull-request
run:
  path: sh
  args:
    - -exc
    - |
      ./scripts/go_deps.sh
      ./scripts/test_unit.sh
  dir: pull-request